### ISSUE TITLE
欠損値について

### ISSUE THREAD

**Issue by shuheimatsugishi** [wm-ytakano/jmardr_cfradial#2]
資料には
・単純圧縮フォーマットにおいて第7節に収録された数値(Z)から、本来の数値(Y)は以下の式で計算すること。Zが全ビット１のときは無効値又は非検出を示す。Y×10^D=R+Z×2^E

とありますがZが全ビット０の間違いなきがします。

**Comment by shuheimatsugishi** [comment]
もしくは全ビット０と1の両方

**Comment by wm-ytakano** [comment]
東京レーダーの場合、すべての変数を見たわけでは無いですが、dBZ, Zdr, Kdp, rhohvは全ビット1で格納されています。全ビット0は空港レーダーの仕様（バグ）でしょうか？

**Comment by shuheimatsugishi** [comment]
仕様が違う可能性もありますね。
空港のは、0は無効値・非検出、1は領域外を示していました。（仕様書をよく読んだら書いてました。）
ドップラー速度以外は0を欠損にしなくても、いい感じ（不具合がない感じ）に出力されるのでドップラーも見ていただけないでしょうか？
Z=0のときドップラー速度は負の非常に大きな値になるので気が付きました。

**Comment by wm-ytakano** [comment]
feature/marge_netcdfブランチの最新版で描いた図を貼っておきます。
仰角0°にしたせいでドップラー速度は折り返しの影響が大きいですが、大きな問題はなさそうです。

![ref](https://user-images.githubusercontent.com/48468500/98314705-ea2cae00-2019-11eb-8890-e8c6e83812ad.png)
![vel](https://user-images.githubusercontent.com/48468500/98314741-003a6e80-201a-11eb-8004-9f6baed44bc8.png)
![vsw](https://user-images.githubusercontent.com/48468500/98314753-04ff2280-201a-11eb-9fef-31555d48260a.png)
![zdr](https://user-images.githubusercontent.com/48468500/98314860-37a91b00-201a-11eb-8da5-46f1c2841397.png)
![psd](https://user-images.githubusercontent.com/48468500/98314867-3c6dcf00-201a-11eb-8d67-099cace502a3.png)
![kdp](https://user-images.githubusercontent.com/48468500/98314875-41328300-201a-11eb-9fc8-98df090b240b.png)
![rhv](https://user-images.githubusercontent.com/48468500/98314890-47286400-201a-11eb-9b77-da78d0a2247f.png)
![qci](https://user-images.githubusercontent.com/48468500/98314907-4d1e4500-201a-11eb-8048-9a5c7e425421.png)

参考までに、古いほうの極座標レーダーデータを描画した図を貼っておきます（ドップラー速度のみ0.3°なのに注意）
![ref_](https://user-images.githubusercontent.com/48468500/98314952-6d4e0400-201a-11eb-8ac5-14529acfe940.png)
![vel_](https://user-images.githubusercontent.com/48468500/98315019-8e165980-201a-11eb-97ed-ccf36f753151.png)

**Comment by shuheimatsugishi** [comment]
確認いただきありがとうございます。仕様の違いですね。お手数おかけしました。
